services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=chat
            - DB_USERNAME=chat
            - DB_PASSWORD=chat

    nginx:
        image: nginx:alpine
        container_name: nginx_server
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: chat
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: chat
            MYSQL_PASSWORD: chat
        volumes:
            - dbdata:/var/lib/mysql

    adminer:
        image: adminer
        container_name: adminer_ui
        restart: unless-stopped
        ports:
            - "8080:8080"

    redis:
        image: redis:alpine
        container_name: redis_cache
        restart: unless-stopped
        ports:
            - "6379:6379"

    echo-server:
        image: node:18
        container_name: echo_server
        working_dir: /app
        restart: unless-stopped
        command: sh -c "npm install -g laravel-echo-server && laravel-echo-server start"
        volumes:
            - .:/app
        ports:
            - "6001:6001"
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis

volumes:
    dbdata:
